ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "fulfillment" TEXT NOT NULL DEFAULT 'PICKUP';
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "deliveryAddress" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "deliveryTime" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "contactPhone" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT;
