CREATE TABLE IF NOT EXISTS aqsi_cash_orders (
  id UUID PRIMARY KEY,
  "orderId" TEXT NOT NULL UNIQUE REFERENCES orders(id),
  "deviceId" INTEGER NOT NULL,
  payload JSONB,
  "operationId" TEXT,
  state TEXT NOT NULL DEFAULT 'QUEUED' CHECK (state IN ('QUEUED','SUBMITTING','WAITING','SUCCEEDED','FAILED','UNKNOWN','BLOCKED','CANCELLED')),
  error TEXT,
  "submittedAt" TIMESTAMPTZ,
  "checkedAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
